src/Entity/Artists.php
<?php

namespace App\Entity;

use App\Repository\ArtistsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
//use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArtistsRepository::class)]
#[UniqueEntity('artist')]
//#[Vich\Uploadable]
class Artists
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true, length: 255)]
    private ?string $filename = null;

    //#[Vich\UploadableField(mapping: 'artists_img', fileNameProperty: 'filename')]
    //private ?File $imageFile = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $artist = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $id_music_styles = null;

    /*#[ORM\Column]
    private ?DateTime $updated_at = null;*/

    /*#[ORM\ManyToOne(inversedBy: 'artists', targetEntity: MusicStyles::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?MusicStyles $musicStyles = null;*/

    #[ORM\ManyToOne(inversedBy: 'artists')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Country $country = null;

    #[ORM\ManyToOne(inversedBy: 'artist', targetEntity: Style::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Style $style = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): self
    {
        $this->artist = $artist;
        return $this;
    }

    public function getIdMusicStyles(): ?string
    {
        return $this->id_music_styles;
    }

    public function setIdMusicStyles(string $id_music_styles): self
    {
        $this->id_music_styles = $id_music_styles;
        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;
        return $this;
    }

    /*public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTimeImmutable('now');
        }
        return $this;
    }*/

    /*public function getUpdatedAt(): ?DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;
        return $this;
    }*/

    /*public function getMusicStyles(): ?MusicStyles
    {
        return $this->musicStyles;
    }

    public function setMusicStyles(?MusicStyles $musicStyles): self
    {
        $this->musicStyles = $musicStyles;
        return $this;
    }*/

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;
        return $this;
    }

    public function getStyle(): ?Style
    {
        return $this->style;
    }

    public function setStyle(?Style $style): self
    {
        $this->style = $style;
        return $this;
    }



}

src/Entity/MusicStyles.php
<?php

namespace App\Entity;

use App\Repository\MusicStylesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: MusicStylesRepository::class)]
#[UniqueEntity('music_style')]
class MusicStyles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_music_styles = null;

    #[ORM\Column(length: 255)]
    private ?string $music_style = null;

    #[ORM\OneToMany(mappedBy: 'style', targetEntity: Artists::class)]
    private Collection $artists;

    public function __construct()
    {
        $this->artists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id_music_styles;
    }

    public function getMusicStyle(): ?string
    {
        return $this->music_style;
    }

    public function setMusicStyle(string $music_style): self
    {
        $this->music_style = $music_style;

        return $this;
    }

    /**
     * @return Collection<int, Artists>
     */
    public function getArtists(): Collection
    {
        return $this->artists;
    }

    public function addArtist(Artists $artist): self
    {
        if (!$this->artists->contains($artist)) {
            $this->artists->add($artist);
            $artist->setStyle($this);
        }

        return $this;
    }

    public function removeArtist(Artists $artist): self
    {
        if ($this->artists->removeElement($artist)) {
            // set the owning side to null (unless already changed)
            if ($artist->getStyle() === $this) {
                $artist->setStyle(null);
            }
        }

        return $this;
    }
}

src/Form/ArtistType.php
<?php

namespace App\Form;

use App\Entity\Artists;
use App\Repository\StyleRepository;
use App\Repository\CountryRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtistType extends AbstractType
{
    private $style_repo;
    private $country_repo;

    public function __construct(StyleRepository $style_repo, CountryRepository $country_repo) {
        $this->style_repo =  $style_repo;
        $this->country_repo =  $country_repo;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('artist', TextType::class, [
                'required' => true,
                'label' => 'Nom',
                'attr' => [
                    'placeholder' => 'Saisir groupe ou artiste'
                ]
            ])
            ->add('style', ChoiceType::class, [
                'required' => false,
                'label' => 'Style',
                'choices' => $this->style_repo->getChoices(),
                'placeholder' => 'Choisir un style'
            ])
            ->add('country', ChoiceType::class, [
                'label' => 'Pays',
                'choices' => $this->country_repo->getChoices(),
                'placeholder' => 'Choisir un pays'
            ])
            ->add('filename', FileType::class, [
                'label' => 'Charger une image',
                'mapped' => false,
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artists::class,
            'translation_domain' => 'forms'
        ]);
    }


}

src/Controller/ArtistsController.php
<?php

namespace App\Controller;

use App\Entity\Artists;
use App\Entity\ArtistSearch;
use App\Entity\MusicStyles;
use App\Form\ArtistSearchType;
use App\Repository\ArtistsRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

class ArtistsController extends AbstractController
{
    private $entity;

    public function __construct(ManagerRegistry $entity, ArtistsRepository $repo) {
        $this->entity = $entity;
        $this->repo = $repo;
    }

    #[Route('/artists', name: 'app_groupes')]
    public function index(PaginatorInterface $paginator, Request $req): Response
    {
        $search = new ArtistSearch();
        $form = $this->createForm(ArtistSearchType::class, $search);
        $form->handleRequest($req);
        $query = $this->repo->findMyChoice($search);
        dump($query);
        $bands = $paginator->paginate(
            $query,
            $req->query->getInt('page', 1),
            12
        );
        dump($bands);

        return $this->render('artists/index.html.twig', [
            'bands' => $bands,
            'form' => $form->createView()
        ]);
    }

    #[Route('/artists/{id}', name: 'app_groupes_show')]
    public function show(Artists $band, PaginatorInterface $paginator, Request $req): Response
    {
        dump($band);
        return $this->render('artists/show.html.twig', [
            'band' => $band
        ]);
    }
}

templates/artists/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Groupes et artistes' %}

{% block body %}

<div class="container">
    <div class="mt-4 mb-5 text-center">
        <h1>Groupes & artistes</h1>
    </div>

    <div class="row col-xs-4 col-md-4 col-lg-3">
        {{ form_start(form) }}
            <form>
                <div class="col">   
                    {{ form_row(form.artistName) }}
                    {{ form_row(form.musicStyle) }}
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary btn-sm">Chercher</button>
                </div>
            </form>
        {{ form_end(form) }}
    </div>

    <div class="row flex">
        {% for band in bands %}
        <div class="my-2 col-xs-4 col-md-4 col-lg-3">
            <a href="{{ path('app_groupes_show', {id:band.id}) }}">
            <!-- modifier le css pour ne pas avoir les textes soulignés en bleu -->
            <div class="card" style="color: #000;">
                <div class="card-body">
                    <div class="card-title">
                        <p>{{ band.artist }}</p>
                    </div>
                    <div class="card-text">
                    <p>
                        {# mettre les styles dans des badges de couleur #}
                        {% if band.IdMusicStyles %}
                            {{ band.IdMusicStyles }} ->  style 
                        {% else %}
                            style
                        {% endif %}
                    </p>
                    </div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="pagination">
        {{ knp_pagination_render(bands) }}
    </div>
</div>

{% endblock %}

templates/artists/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Page {{ band.artist }} {% endblock %}

{% block body %}

<div class="container" style="border:1px solid grey;">
    <div class="my-5 row col-lg-12 col-md-12 col-sm-12 text-center" style="justify-content: space-evenly;">
    	<div class="col-auto mb-3">
    		<img src="{{ asset('images/artists/' ~ band.filename) }}" alt="photo {{ band.artist }}" width="300px"/>
    	</div>
		<div class="col-auto text-center">
    		<h1>{{ band.artist }}</h1>
    		<span class="mx-3">Style : {{ band.idMusicStyles }}</span>
    		<span class="mx-3">Pays : Islande</span>
    	</div>
    </div>



</div>

{% endblock %}